development:
  adapter: sqlite3
  encoding: unicode
  database:  --database_dev
  pool: 5
  username: Adam
  password:
test:
  adapter: postgresql
  encoding: unicode
  database:  --database_test
  pool: 5
  username: Adam
  password:

production:
  adapter: postgresql
  encoding: unicode
  database:  --database_production
  pool: 5
  username: Adam
  password:
